### ISSUE TITLE
Error with running example codes. 

### ISSUE THREAD

**Issue by visuelledata** [simonpcouch/anyflights#1]
```
 anyflights(station = "PDX", year = 2015, dir = tempdir())
Error in FUN(X[[i]], ...) : 
  Can't access flight data for supplied year. Check date of 'Latest Available Data' for 'Airline On-Time Performance Data' on 
 https://www.transtats.bts.gov/releaseinfo.asp
```

When I run most of the get_ functions I get errors similar to this one.

**Comment by andrewpbray** [comment]
Hey @simonpcouch , I'm running into a similar problem. Can you tell if BTS has changed their formatting?

**Comment by simonpcouch** [comment]
Hey @visuelledata @andrewpbray — looks a pretty major change in how BTS reports/releases the flights data happened in August. Thanks for bringing this up, will start working on a fix.

**Comment by ismayc** [comment]
Hi @simonpcouch. Any updates here? I'd like to analyze humidity versus temperature across different regions in the US for a given year but I'm getting the same error reported here.

**Comment by simonpcouch** [comment]
@visuelledata @andrewpbray @ismayc My apologies for not keeping this issue updated--I reached out to CRAN recently to let them know this package is no longer being maintained, and have just pushed some notes to the master branch reflecting this change.
