### ISSUE TITLE
Add in more messaging while downloading

### ISSUE THREAD

**Issue by ismayc** [simonpcouch/anyflights#4]
Love that this is back on CRAN! Congrats on getting it up there again, Simon!

Given it does take some time to download data, could some messages be added letting users know of where they are in the process? Something like

> `Downloading flights data for SEA`

**Comment by ismayc** [comment]
Might be nice to also tell users how long it took for each of the items to download so they could plan accordingly on other airport downloads too?

**Comment by simonpcouch** [comment]
Thanks @ismayc! Really appreciate both of these ideas, and will put some time in on adding some messaging in here soon.

**Comment by simonpcouch** [comment]
Thanks again for the issue, @ismayc! Was conflicted about what progress updates should look like, but the idea of just supplying what's currently being downloaded and the elapsed time to that point was a really fitting approach.

Progress updates have been implemented on `develop` for `get_flights()` and `anyflights()`—let me know if you have any thoughts!

**Comment by ismayc** [comment]
Nice! That's pretty slick. Here it is in action: https://www.loom.com/share/e39f6ab35aec4b1bb4ddc16d2fc5f0a5

**Comment by ismayc** [comment]
Looks good to me!
