### ISSUE TITLE
refactor get_weather() tidying

### ISSUE THREAD

**Issue by simonpcouch** [simonpcouch/anyflights#8]
[From Hannes Becker on Twitter:](https://twitter.com/SportsTribution/status/1257211614887018496)

> Another problem I ran into with my scrape case (I realize, I'm not using the package as it's supposed to, so it's more of an FYI): The raw weather data is quite big (>100k obs per airport), so if I first download all airports (weather_raw) and then do the munging it breaks. The solution might simply be to move the '# tidy the data part' (line 76 ff in get_weather) to the get_weather_for_station function. But once again, this is just an FYI. I should probably make my I branch and should be more helpful, but my brain's not awake enough for git rn. :)

**Comment by denironyx** [comment]
HI @simonpcouch ,  I think I might be able to take a look at this. Are you already working on this?

**Comment by simonpcouch** [comment]
@denironyx I'm not, no! Looks like some copying + pasting will do the trick—feel free to PR to `develop` if you end up putting some time into this.🙂

**Comment by simonpcouch** [comment]
Hey @denironyx! I went ahead and made this fix, but thanks for the interest.
